import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { SiteLayout, PageHeader, SectionHeading } from "@/components/site/SiteLayout";
import { Reveal } from "@/components/site/Reveal";
import { Button } from "@/components/ui/button";
import craft from "@/assets/custom-framing-craft.jpg";
import gallery from "@/assets/art-collection-gallery.jpg";
const url="https://shaheencarrenatl.lovable.app/about";
export const Route=createFileRoute("/about")({head:()=>({meta:[{title:"About Frame Frosh | Art & Framing Studio Lahore"},{name:"description",content:"Meet the people behind Frame Frosh, a Lahore studio devoted to paintings, custom framing and thoughtful artistic presentation."},{property:"og:title",content:"About Frame Frosh | Art & Framing Studio Lahore"},{property:"og:description",content:"Craftsmanship, artistic presentation and personal service in Lahore."},{property:"og:type",content:"website"},{property:"og:url",content:url},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:url}]}),component:AboutPage});
function AboutPage(){return <SiteLayout><PageHeader eyebrow="About us" title={<>The people behind <em>Frame Frosh.</em></>} blurb="We bring together art, proportion and careful finishing to create pieces that feel made for their place."/><section className="py-20"><div className="mx-auto grid max-w-7xl gap-5 px-5 lg:grid-cols-2 lg:px-8"><Reveal><img src={craft} alt="Frame Frosh craftsmanship" width={1600} height={1200} className="h-full min-h-[400px] w-full object-cover"/></Reveal><Reveal delay={100}><img src={gallery} alt="A curated display of paintings and frames" width={1600} height={1200} className="h-full min-h-[400px] w-full object-cover"/></Reveal></div></section><section className="bg-secondary py-24"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-2 lg:px-8"><SectionHeading eyebrow="Our point of view" title="Art deserves a thoughtful setting."/><div><p className="text-base leading-8 text-muted-foreground">Frame Frosh is a Lahore-based destination for framed paintings, wall art and custom picture framing. Our approach begins with the piece itself—its colour, scale and character—then considers the room it will inhabit.</p><p className="mt-5 text-base leading-8 text-muted-foreground">Whether you are choosing artwork or preserving something personal, our focus is simple: attentive guidance, balanced presentation and a finish that lets the work speak.</p><Button asChild className="mt-8"><Link to="/contact">Talk to our team <ArrowRight/></Link></Button></div></div></section></SiteLayout>}