import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check } from "lucide-react";
import { SiteLayout, PageHeader, SectionHeading } from "@/components/site/SiteLayout";
import { Reveal } from "@/components/site/Reveal";
import { Button } from "@/components/ui/button";
import { frameStyles } from "@/components/site/data";
import craft from "@/assets/custom-framing-craft.jpg";
const url="https://shaheencarrenatl.lovable.app/custom-framing";
export const Route=createFileRoute("/custom-framing")({head:()=>({meta:[{title:"Custom Picture Framing Lahore | Frame Frosh"},{name:"description",content:"Custom framing in Lahore for paintings, portraits, photographs, certificates, memorabilia and textile art."},{property:"og:title",content:"Custom Picture Framing Lahore | Frame Frosh"},{property:"og:description",content:"Thoughtful custom frames made around your artwork and space."},{property:"og:type",content:"website"},{property:"og:url",content:url},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:url}]}),component:FramingPage});
function FramingPage(){return <SiteLayout><PageHeader eyebrow="Custom framing Lahore" title={<>Made To Frame <em>Your Story.</em></>} blurb="Every meaningful piece deserves a presentation considered around its character, scale and future home."/><section className="py-20"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 lg:grid-cols-2 lg:px-8"><Reveal><img src={craft} alt="Custom picture frame craftsmanship" width={1600} height={1200} className="aspect-[4/3] size-full object-cover"/></Reveal><Reveal delay={100}><SectionHeading eyebrow="What we frame" title="Personal pieces, precisely presented."/><div className="mt-8 grid gap-3 sm:grid-cols-2">{["Paintings","Portraits","Photographs","Certificates","Memorabilia","Textile and art pieces","Decorative artwork","Custom-size pieces"].map(x=><p key={x} className="flex items-center gap-3 text-sm"><Check className="size-4 text-primary"/>{x}</p>)}</div><Button asChild className="mt-9"><Link to="/contact">Request Custom Framing <ArrowRight/></Link></Button></Reveal></div></section><section className="bg-secondary py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionHeading eyebrow="Frame profiles" title="Choose the finishing note."/><div className="mt-10 grid grid-cols-2 gap-4 md:grid-cols-3">{frameStyles.map(s=><div key={s.name} className="bg-background p-5"><div className={`h-20 border-[12px] ${s.tone}`}><div className="size-full bg-secondary"/></div><p className="mt-4 font-serif text-xl">{s.name}</p></div>)}</div></div></section></SiteLayout>}